server:
  port: 8086

spring:
  application:
    name: notification
  datasource:
    username: services
    url: jdbc:postgresql://localhost:5432/notification
    password: password
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

rabbitmq:
  template:
    exchanges:
      internal: internal.exchange
    queue:
      notification: notification.queue
    routing-keys:
      internal-notification: internal.notification.routing-key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false